import React, { useState, useRef, useEffect } from 'react';
import {
  Box,
  Input,
  VStack,
  HStack,
  Text,
  IconButton,
  Button,
  Spinner,
  Flex,
  Icon,
} from '@chakra-ui/react';
import { FiSend, FiCheck } from 'react-icons/fi';
import { useHistory } from 'react-router-dom';
import { useAppStore } from '../../store';
import { sendMessageToGemini } from '../../services/geminiService';
import { Message } from '../../types/chat';
import { Quote, QuoteItem } from '../../types/quote';
import { saveChatHistory, loadChatHistory } from '../../utils/localStorage';

const SUGGESTION_PROMPTS = [
  'Generate quote for 100 auto full branding',
  'Create quote for banner printing 10x5 feet, qty 50',
  'Quote for vehicle branding – 20 tempos',
  'Generate quote for shop signage',
  'Create quote for the services in proposal',
];

const ChatInterface: React.FC = () => {
  const history = useHistory();
  const { proposal, setCurrentQuote } = useAppStore();
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [_error, setError] = useState<string | null>(null);
  const [isRecording, setIsRecording] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const recognitionRef = useRef<any>(null);

  // Load chat history on mount
  useEffect(() => {
    const history = loadChatHistory();
    if (history && history.length > 0) {
      setMessages(history.map(msg => ({
        ...msg,
        timestamp: new Date(msg.timestamp),
      })));
    }
  }, []);

  // Save chat history when messages change
  useEffect(() => {
    if (messages.length > 0) {
      saveChatHistory(messages);
    }
  }, [messages]);

  // Scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  const handleSendMessage = async () => {
    if (!inputValue.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: inputValue.trim(),
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    setIsLoading(true);
    setError(null);

    try {
      const response = await sendMessageToGemini({
        userMessage: userMessage.content,
        proposalText: proposal.textContent,
        chatHistory: messages,
      });

      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: response.message,
        timestamp: new Date(),
      };

      setMessages(prev => [...prev, assistantMessage]);

      // If complete quote was generated by AI, store it and AUTO-NAVIGATE
      if (response.isQuoteGeneration && response.quoteData) {
        // Flatten lineItems into individual QuoteItems
        // IMPORTANT: Prepend section title to each description for matching with PDF pages
        const quoteItems: QuoteItem[] = response.quoteData.items.flatMap((section: any, sectionIndex: number) => {
          const sectionTitle = section.title || '';
          return section.lineItems.map((item: any, lineIndex: number) => {
            // If description doesn't already contain the section title, prepend it
            let description = item.description;
            if (sectionTitle && !description.toLowerCase().includes(sectionTitle.toLowerCase())) {
              description = `${sectionTitle} - ${description}`;
            }
            
            const duration = item.duration && item.duration > 1 ? item.duration : undefined;
            return {
              id: `${sectionIndex}-${lineIndex}`,
              description: description,
              quantity: item.quantity || 1,
              rate: item.unitPrice || 0,
              duration: duration,
              total: (item.quantity || 1) * (item.unitPrice || 0) * (duration || 1),
              // Only store terms on the first line item of each section to avoid duplicate textareas
              termsAndConditions: lineIndex === 0 ? (section.termsAndConditions || undefined) : undefined
            };
          });
        });

        const subtotal = quoteItems.reduce((sum, item) => sum + item.total, 0);
        const gstPercentage = 18;
        const gstAmount = subtotal * (gstPercentage / 100);
        
        const quote: Quote = {
          id: Date.now().toString(),
          quoteNumber: `QT-${Date.now().toString().slice(-6)}`,
          date: new Date().toISOString(),
          validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
          items: quoteItems,
          subtotal,
          gstEnabled: true,
          gstPercentage,
          gstAmount,
          total: subtotal + gstAmount,
          deliveryTimeline: response.quoteData.deliveryTimeline || '7 working days after payment',
          termsAndConditions: response.quoteData.termsAndConditions || 'Standard terms and conditions apply',
          notes: response.quoteData.notes,
          createdAt: new Date(),
          updatedAt: new Date()
        };
        
        setCurrentQuote(quote);
        
        // Show success message before navigating
        const quoteReadyMessage: Message = {
          id: (Date.now() + 2).toString(),
          role: 'assistant',
          content: '✓ Quote generated successfully! Redirecting to quote preview...',
          timestamp: new Date(),
        };
        setMessages(prev => [...prev, quoteReadyMessage]);
        
        // Auto-navigate to quote page after a brief delay
        setTimeout(() => {
          history.push('/quote');
        }, 1500);
      }
    } catch (err: any) {
      console.error('Chat error:', err);
      setError(err.message || 'Failed to send message');
      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: err.message || 'Sorry, I encountered an error. Please try again.',
        timestamp: new Date(),
        isError: true,
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSuggestionClick = (suggestion: string) => {
    setInputValue(suggestion);
  };

  // Initialize speech recognition
  useEffect(() => {
    if ('webkitSpeechRecognition' in window || 'SpeechRecognition' in window) {
      const SpeechRecognition = (window as any).webkitSpeechRecognition || (window as any).SpeechRecognition;
      const recognition = new SpeechRecognition();
      recognition.continuous = false;
      recognition.interimResults = false;
      recognition.lang = 'en-US';

      recognition.onresult = (event: any) => {
        const transcript = event.results[0][0].transcript;
        setInputValue(prev => prev + (prev ? ' ' : '') + transcript);
        setIsRecording(false);
      };

      recognition.onerror = (event: any) => {
        console.error('Speech recognition error:', event.error);
        setIsRecording(false);
      };

      recognition.onend = () => {
        setIsRecording(false);
      };

      recognitionRef.current = recognition;
    }

    return () => {
      if (recognitionRef.current) {
        recognitionRef.current.stop();
      }
    };
  }, []);

  return (
    <Box
      display="flex"
      flexDirection="column"
      h={{ base: 'auto', lg: 'calc(100vh - 520px)' }}
      minH={{ base: '350px', lg: '400px' }}
      maxH={{ base: 'calc(100vh - 250px)', lg: 'calc(100vh - 300px)' }}
      borderRadius="14px"
      border="1px solid"
      borderColor="gray.200"
      overflow="hidden"
      bg="white"
    >
      {/* Header - AI Assistant with Online Status */}
      <HStack
        justify="space-between"
        align="center"
        px={5}
        py={4}
        bgGradient="linear(90deg, gray.900, #1A1A2E)"
      >
        <HStack spacing={2}>
          <Box
            bgGradient="linear(135deg, purple.500, red.600)"
            color="white"
            w="32px"
            h="32px"
            borderRadius="8px"
            display="flex"
            alignItems="center"
            justifyContent="center"
            fontSize="sm"
            fontWeight="700"
          >
            G
          </Box>
          <Text fontSize="md" fontWeight="600" color="white">
            Quote Assistant
          </Text>
        </HStack>
        <HStack spacing={1}>
          <Box 
            w="8px" 
            h="8px" 
            borderRadius="full" 
            bg="teal.400"
            sx={{
              animation: 'pulse 2s infinite',
              '@keyframes pulse': {
                '0%,100%': { opacity: 1 },
                '50%': { opacity: 0.4 },
              },
            }}
          />
          <Text fontSize="xs" color="teal.400" fontWeight="500">
            Online
          </Text>
        </HStack>
      </HStack>

      {/* Content Area */}
      <VStack align="stretch" spacing={4} flex={1} overflow="hidden" p={4}>
        {/* Suggestion Chips */}
        {messages.length === 0 && (
          <Box px={2}>
            <Text fontSize="xs" fontWeight="500" color="gray.500" mb={2}>
              Try asking:
            </Text>
            <VStack align="stretch" spacing={2}>
              {SUGGESTION_PROMPTS.map((prompt, index) => (
                <Button
                  key={index}
                  variant="outline"
                  borderColor="gray.300"
                  color="gray.700"
                  size="sm"
                  justifyContent="flex-start"
                  textAlign="left"
                  whiteSpace="normal"
                  h="auto"
                  py={2}
                  px={3}
                  borderRadius="full"
                  fontWeight="400"
                  fontSize="11px"
                  onClick={() => handleSuggestionClick(prompt)}
                  _hover={{
                    bg: 'red.50',
                    borderColor: 'red.500',
                    color: 'red.600',
                  }}
                >
                  {prompt}
                </Button>
              ))}
            </VStack>
          </Box>
        )}

        {/* AI Response Output Area */}
        <Box
          flex={1}
          bg="gray.50"
          borderRadius="lg"
          p={{ base: 3, md: 3 }}
          overflowY="auto"
          minH="0"
          sx={{ 
            '::-webkit-scrollbar': { 
              width: '6px',
            },
            '::-webkit-scrollbar-track': {
              background: 'transparent',
            },
            '::-webkit-scrollbar-thumb': {
              background: 'gray.300',
              borderRadius: '3px',
            },
          }}
        >
          {messages.length === 0 ? (
            <Flex justify="center" align="center" h="full">
              <Text color="gray.400" fontSize="xs">
                {proposal.textContent
                  ? 'Upload a PDF and ask me anything about it.'
                  : 'Upload a proposal to start chatting'}
              </Text>
            </Flex>
          ) : (
            <VStack align="stretch" spacing={5}>
              {messages.map(message => {
                // Parse message content for special formatting
                const lines = message.content.split('\n');
                const hasQuoteHeader = lines[0]?.toLowerCase().includes('quote generated');

                // Helper: bold key summary values
                function boldSummary(line: string) {
                  // Bold numbers and key phrases (e.g., 5 Mobile LED Vans, 3 months)
                  return line.replace(/(\d+\s+Mobile LED Vans|\d+\s+months?|\d+\s+LED vans?|\d+\s+vans?)/gi, '<b>$1</b>');
                }

                return (
                  <Box
                    key={message.id}
                    alignSelf={message.role === 'user' ? 'flex-end' : 'flex-start'}
                    maxW={message.role === 'user' ? '80%' : '90%'}
                  >
                    {message.role === 'assistant' && hasQuoteHeader ? (
                      // Special format for quote generation messages
                      <Box>
                        {/* Quote Header Badge */}
                        <HStack 
                          spacing={2} 
                          mb={3} 
                          align="center"
                          bg="linear-gradient(135deg, #e6f7ff 0%, #e0f2fe 100%)"
                          px={4}
                          py={2.5}
                          borderRadius="12px"
                          border="1px solid"
                          borderColor="blue.200"
                          boxShadow="0 2px 6px rgba(14, 165, 233, 0.15)"
                        >
                          <Icon 
                            as={FiCheck} 
                            color="blue.600" 
                            boxSize="16px"
                            fontWeight="bold"
                          />
                          <Text
                            fontSize="13px"
                            fontWeight="700"
                            color="blue.700"
                            letterSpacing="tight"
                          >
                            {lines[0]}
                          </Text>
                        </HStack>

                        {/* Response Card */}
                        <Box
                          bg="white"
                          border="1px solid"
                          borderColor="gray.200"
                          px={{ base: 4, md: 5 }}
                          py={{ base: 4, md: 5 }}
                          borderRadius="14px"
                          boxShadow="0 4px 12px rgba(0, 0, 0, 0.06), 0 1px 3px rgba(0, 0, 0, 0.08)"
                        >
                          <VStack align="stretch" spacing={2.5}>
                            {(() => {
                              // Filter out all lines inside ```json ... ``` code blocks
                              let inCodeBlock = false;
                              return lines.slice(1).map((line, idx) => {
                                if (line.trim().startsWith('```json')) { inCodeBlock = true; return null; }
                                if (inCodeBlock && line.trim() === '```') { inCodeBlock = false; return null; }
                                if (inCodeBlock) return null;
                                if (!line.trim()) return null;
                                return (
                                  <Text 
                                    key={idx} 
                                    fontSize="14px" 
                                    color="gray.700" 
                                    lineHeight="1.7"
                                    fontWeight="500"
                                    dangerouslySetInnerHTML={{ __html: boldSummary(line) }} 
                                  />
                                );
                              });
                            })()}
                          </VStack>

                          {/* Code Block - if message contains JSON */}
                          {message.content.includes('```json') && (() => {
                            const raw = message.content.match(/```json\n([\s\S]*?)```/)?.[1] || '';
                            // Enhanced syntax highlighting
                            const highlighted = raw.replace(
                              /("(?:[^"\\]|\\.)*")\s*(:)|("(?:[^"\\]|\\.)*")|(true|false|null)|(\d+(?:\.\d+)?)/g,
                              (match: string, key: string, colon: string, str: string, bool: string, num: string) => {
                                if (key && colon) return `<span style="color:#fbbf24; font-weight:600">${key}</span><span style="color:#9ca3af">${colon}</span>`;
                                if (str) return `<span style="color:#34d399">${str}</span>`;
                                if (bool) return `<span style="color:#60a5fa; font-weight:600">${bool}</span>`;
                                if (num) return `<span style="color:#a78bfa; font-weight:600">${num}</span>`;
                                return match;
                              }
                            );
                            return (
                              <Box
                                bg="linear-gradient(135deg, #1e293b 0%, #0f172a 100%)"
                                p={4}
                                borderRadius="12px"
                                fontSize="12px"
                                fontFamily="'Consolas', 'Monaco', monospace"
                                overflowX="auto"
                                mt={4}
                                maxW={{ base: '100%', md: '380px' }}
                                border="1px solid"
                                borderColor="gray.700"
                                boxShadow="inset 0 2px 4px rgba(0,0,0,0.3), 0 2px 8px rgba(0,0,0,0.15)"
                                sx={{
                                  '::-webkit-scrollbar': { height: '6px' },
                                  '::-webkit-scrollbar-track': { bg: 'whiteAlpha.100', borderRadius: '3px' },
                                  '::-webkit-scrollbar-thumb': { bg: 'whiteAlpha.300', borderRadius: '3px' },
                                }}
                              >
                                <Box
                                  as="pre"
                                  whiteSpace="pre"
                                  fontSize="12px"
                                  fontFamily="'Consolas', 'Monaco', monospace"
                                  color="#e5e7eb"
                                  lineHeight="1.6"
                                  m={0}
                                  dangerouslySetInnerHTML={{ __html: highlighted }}
                                />
                              </Box>
                            );
                          })()}
                        </Box>
                      </Box>
                    ) : (
                      // Regular message format
                      <Box
                        bgGradient={message.role === 'user' 
                          ? 'linear(135deg, #dc2626 0%, #be123c 50%, #9f1239 100%)' 
                          : undefined
                        }
                        bg={message.role === 'user' ? undefined : 'white'}
                        border={message.role === 'user' ? 'none' : '1px solid'}
                        borderColor={message.role === 'user' ? undefined : 'gray.200'}
                        color={message.role === 'user' ? 'white' : 'gray.800'}
                        px={{ base: 4, md: 5 }}
                        py={{ base: 3.5, md: 4 }}
                        borderRadius={message.role === 'user' ? '20px 20px 4px 20px' : '4px 16px 16px 16px'}
                        boxShadow={message.role === 'user' 
                          ? '0 8px 16px rgba(220, 38, 38, 0.25), 0 2px 4px rgba(220, 38, 38, 0.1)' 
                          : '0 4px 12px rgba(0, 0, 0, 0.06), 0 1px 3px rgba(0, 0, 0, 0.08)'
                        }
                      >
                        <Text 
                          fontSize="14px" 
                          whiteSpace="pre-wrap"
                          lineHeight="1.6"
                          fontWeight="500"
                        >
                          {message.content}
                        </Text>
                        <Text
                          fontSize="11px"
                          mt={2}
                          opacity={message.role === 'user' ? 0.75 : 0.6}
                          fontWeight="500"
                          letterSpacing="tight"
                        >
                          {message.timestamp.toLocaleTimeString([], {
                            hour: '2-digit',
                            minute: '2-digit',
                          })}
                        </Text>
                      </Box>
                    )}
                  </Box>
                );
              })}

              {/* Typing Indicator */}
              {isLoading && (
                <Box alignSelf="flex-start">
                  <HStack
                    spacing={1.5}
                    px={4}
                    py={3}
                    bg="white"
                    border="1px solid"
                    borderColor="gray.200"
                    borderRadius="4px 14px 14px 14px"
                    boxShadow="0 4px 12px rgba(0, 0, 0, 0.06), 0 1px 3px rgba(0, 0, 0, 0.08)"
                  >
                    {[0, 1, 2].map(i => (
                      <Box
                        key={i}
                        w="7px"
                        h="7px"
                        borderRadius="full"
                        bg="blue.500"
                        sx={{
                          animation: `bounce 1.2s ${i * 0.2}s infinite ease-in-out`,
                          '@keyframes bounce': {
                            '0%,100%': { transform: 'translateY(0)', opacity: 0.5 },
                            '50%': { transform: 'translateY(-8px)', opacity: 1, boxShadow: '0 0 8px rgba(59, 130, 246, 0.5)' },
                          },
                        }}
                      />
                    ))}
                  </HStack>
                </Box>
              )}

              <div ref={messagesEndRef} />
            </VStack>
          )}
        </Box>

        {/* Bottom Chat Input Bar */}
        <HStack 
          spacing={3} 
          flexShrink={0} 
          px={4}
          py={3}
          borderTop="2px solid"
          borderColor="gray.200"
          bg="white"
          boxShadow="0 -2px 10px rgba(0, 0, 0, 0.05)"
        >
          <Input
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyPress={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                handleSendMessage();
              }
            }}
            placeholder={
              proposal.textContent
                ? 'Ask about this proposal…'
                : 'Upload a proposal to start…'
            }
            disabled={isLoading || !proposal.textContent}
            size="md"
            borderRadius="full"
            bg="white"
            border="2px solid"
            borderColor="gray.300"
            color="gray.900"
            fontSize="14px"
            h="48px"
            w="100%"
            px={5}
            fontWeight="500"
            _placeholder={{ color: 'gray.500', fontSize: '14px' }}
            _hover={{ 
              borderColor: 'red.400',
              boxShadow: '0 0 0 1px rgba(220, 38, 38, 0.1)',
            }}
            _focus={{
              borderColor: 'red.500',
              boxShadow: '0 0 0 3px rgba(220, 38, 38, 0.1)',
              outline: 'none',
            }}
            _disabled={{
              bg: 'gray.100',
              color: 'gray.500',
              cursor: 'not-allowed',
              opacity: 0.6,
            }}
          />
          <Box position="relative" display="inline-flex" alignItems="center" justifyContent="center">
            {/* Listening indicator text */}
            {isRecording && (
              <Text
                position="absolute"
                top="-28px"
                fontSize="xs"
                fontWeight="600"
                color="red.500"
                bg="white"
                px={3}
                py={1}
                borderRadius="full"
                boxShadow="0 2px 8px rgba(239, 68, 68, 0.2)"
                border="1px solid"
                borderColor="red.200"
                whiteSpace="nowrap"
                sx={{
                  animation: 'fadeIn 0.3s ease-in-out',
                  '@keyframes fadeIn': {
                    from: { opacity: 0, transform: 'translateY(4px)' },
                    to: { opacity: 1, transform: 'translateY(0)' },
                  },
                }}
              >
                🎙️ Listening...
              </Text>
            )}
            
            {/* Animated rings when recording */}
            {isRecording && (
              <>
                <Box
                  position="absolute"
                  w="48px"
                  h="48px"
                  borderRadius="full"
                  border="2px solid"
                  borderColor="red.400"
                  sx={{
                    animation: 'ripple 1.5s ease-out infinite',
                    '@keyframes ripple': {
                      '0%': { 
                        transform: 'scale(1)',
                        opacity: 0.8,
                      },
                      '100%': { 
                        transform: 'scale(1.8)',
                        opacity: 0,
                      },
                    },
                  }}
                />
                <Box
                  position="absolute"
                  w="48px"
                  h="48px"
                  borderRadius="full"
                  border="2px solid"
                  borderColor="red.300"
                  sx={{
                    animation: 'ripple 1.5s ease-out infinite 0.5s',
                    '@keyframes ripple': {
                      '0%': { 
                        transform: 'scale(1)',
                        opacity: 0.8,
                      },
                      '100%': { 
                        transform: 'scale(1.8)',
                        opacity: 0,
                      },
                    },
                  }}
                />
              </>
            )}
            
            {/* Voice input button hidden */}
            {/* <IconButton
              aria-label={isRecording ? "Stop recording" : "Voice input"}
              icon={<FiMic />}
              onClick={toggleVoiceInput}
              isDisabled={isLoading || !proposal.textContent}
              bgGradient={isRecording 
                ? "linear(to-br, red.500, red.600, pink.500)" 
                : "linear(to-br, blue.500, blue.600, cyan.500)"
              }
              color="white"
              size="md"
              h="48px"
              w="48px"
              minW="48px"
              borderRadius="full"
              flexShrink={0}
              fontSize="20px"
              position="relative"
              zIndex={1}
              border="2px solid"
              borderColor={isRecording ? "red.300" : "blue.300"}
              boxShadow={isRecording 
                ? "0 4px 20px rgba(239, 68, 68, 0.5), 0 0 30px rgba(239, 68, 68, 0.3), inset 0 1px 0 rgba(255,255,255,0.3)" 
                : "0 4px 16px rgba(59, 130, 246, 0.4), 0 0 24px rgba(59, 130, 246, 0.2), inset 0 1px 0 rgba(255,255,255,0.3)"
              }
              _hover={{
                bgGradient: isRecording 
                  ? "linear(to-br, red.600, red.700, pink.600)" 
                  : "linear(to-br, blue.600, blue.700, cyan.600)",
                transform: 'translateY(-2px) scale(1.05)',
                boxShadow: isRecording 
                  ? '0 8px 28px rgba(239, 68, 68, 0.6), 0 0 40px rgba(239, 68, 68, 0.4), inset 0 1px 0 rgba(255,255,255,0.4)' 
                  : '0 8px 24px rgba(59, 130, 246, 0.5), 0 0 32px rgba(59, 130, 246, 0.3), inset 0 1px 0 rgba(255,255,255,0.4)',
                borderColor: isRecording ? "red.200" : "blue.200",
              }}
              _active={{
                transform: 'scale(0.95)',
                boxShadow: isRecording 
                  ? '0 2px 12px rgba(239, 68, 68, 0.4), inset 0 2px 4px rgba(0,0,0,0.2)' 
                  : '0 2px 12px rgba(59, 130, 246, 0.4), inset 0 2px 4px rgba(0,0,0,0.2)',
              }}
              _disabled={{
                bgGradient: 'linear(to-br, gray.300, gray.400)',
                color: 'gray.500',
                cursor: 'not-allowed',
                opacity: 0.6,
                boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
                borderColor: 'gray.300',
              }}
              sx={isRecording ? {
                animation: 'micPulse 1.2s ease-in-out infinite',
                '@keyframes micPulse': {
                  '0%, 100%': { 
                    transform: 'scale(1)',
                    filter: 'brightness(1)',
                  },
                  '50%': { 
                    transform: 'scale(1.08)',
                    filter: 'brightness(1.15)',
                  },
                },
              } : {
                transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
              }}
            /> */}
          </Box>
          <IconButton
            aria-label="Send message"
            icon={isLoading ? <Spinner size="sm" color="white" /> : <FiSend />}
            onClick={handleSendMessage}
            isDisabled={!inputValue.trim() || isLoading || !proposal.textContent}
            bgGradient="linear(to-r, #dc2626, #be123c)"
            color="white"
            size="md"
            h="48px"
            w="48px"
            minW="48px"
            borderRadius="full"
            flexShrink={0}
            fontSize="20px"
            boxShadow="0 4px 12px rgba(220, 38, 38, 0.3)"
            _hover={{
              bgGradient: "linear(to-r, #be123c, #9f1239)",
              transform: 'translateY(-1px)',
              boxShadow: '0 6px 16px rgba(220, 38, 38, 0.4)',
            }}
            _active={{
              transform: 'scale(0.95)',
              boxShadow: '0 2px 8px rgba(220, 38, 38, 0.3)',
            }}
            _disabled={{
              bgGradient: 'linear(to-r, gray.200, gray.300)',
              color: 'white',
              cursor: 'not-allowed',
              opacity: 0.75,
              boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
              filter: 'grayscale(0.3)',
            }}
          />
        </HStack>
      </VStack>
    </Box>
  );
};

export default ChatInterface;
