import React, { useState, useRef, useEffect } from 'react';
import {
  Box,
  Input,
  VStack,
  HStack,
  Text,
  IconButton,
  Button,
  Card,
  CardBody,
  CardHeader,
  Heading,
  Spinner,
  Flex,
} from '@chakra-ui/react';
import { FiSend } from 'react-icons/fi';
import { useHistory } from 'react-router-dom';
import { useAppStore } from '../../store';
import { sendMessageToGemini } from '../../services/geminiService';
import { Message } from '../../types/chat';
import { Quote, QuoteItem } from '../../types/quote';
import { saveChatHistory, loadChatHistory } from '../../utils/localStorage';

const SUGGESTION_PROMPTS = [
  'Generate quote for 100 auto full branding',
  'Create quote for banner printing 10x5 feet, qty 50',
  'Quote for vehicle branding – 20 tempos',
  'Generate quote for shop signage',
  'Create quote for the services in proposal',
];

const ChatInterface: React.FC = () => {
  const history = useHistory();
  const { proposal, setCurrentQuote } = useAppStore();
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [_error, setError] = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Load chat history on mount
  useEffect(() => {
    const history = loadChatHistory();
    if (history && history.length > 0) {
      setMessages(history.map(msg => ({
        ...msg,
        timestamp: new Date(msg.timestamp),
      })));
    }
  }, []);

  // Save chat history when messages change
  useEffect(() => {
    if (messages.length > 0) {
      saveChatHistory(messages);
    }
  }, [messages]);

  // Scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  const handleSendMessage = async () => {
    if (!inputValue.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: inputValue.trim(),
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    setIsLoading(true);
    setError(null);

    try {
      const response = await sendMessageToGemini({
        userMessage: userMessage.content,
        proposalText: proposal.textContent,
        chatHistory: messages,
      });

      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: response.message,
        timestamp: new Date(),
      };

      setMessages(prev => [...prev, assistantMessage]);

      // If complete quote was generated by AI, store it and AUTO-NAVIGATE
      if (response.isQuoteGeneration && response.quoteData) {
        // Convert AI-generated quote data to Quote object
        const quoteItems: QuoteItem[] = response.quoteData.items.map((section: any, index: number) => {
          const lineItems = section.lineItems.map((item: any, lineIndex: number) => ({
            id: `${index}-${lineIndex}`,
            description: item.description,
            quantity: item.quantity || 1,
            unitPrice: item.unitPrice || 0,
            total: (item.quantity || 1) * (item.unitPrice || 0)
          }));

          const sectionSubtotal = lineItems.reduce((sum: number, item: any) => sum + item.total, 0);

          return {
            id: index.toString(),
            title: section.title,
            description: section.title,
            quantity: 1,
            rate: sectionSubtotal,
            total: sectionSubtotal,
            lineItems,
            subtotal: sectionSubtotal
          };
        });

        const subtotal = quoteItems.reduce((sum, item) => sum + item.total, 0);
        const gstPercentage = 18;
        const gstAmount = subtotal * (gstPercentage / 100);
        
        const quote: Quote = {
          id: Date.now().toString(),
          quoteNumber: `QT-${Date.now().toString().slice(-6)}`,
          date: new Date().toISOString(),
          validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
          items: quoteItems,
          subtotal,
          gstEnabled: true,
          gstPercentage,
          gstAmount,
          total: subtotal + gstAmount,
          deliveryTimeline: response.quoteData.deliveryTimeline || '7 working days after payment',
          termsAndConditions: response.quoteData.termsAndConditions || 'Standard terms and conditions apply',
          notes: response.quoteData.notes,
          createdAt: new Date(),
          updatedAt: new Date()
        };
        
        setCurrentQuote(quote);
        
        // Show success message before navigating
        const quoteReadyMessage: Message = {
          id: (Date.now() + 2).toString(),
          role: 'assistant',
          content: '✓ Quote generated successfully! Redirecting to quote preview...',
          timestamp: new Date(),
        };
        setMessages(prev => [...prev, quoteReadyMessage]);
        
        // Auto-navigate to quote page after a brief delay
        setTimeout(() => {
          history.push('/quote');
        }, 1500);
      }
    } catch (err: any) {
      console.error('Chat error:', err);
      setError(err.message || 'Failed to send message');
      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: err.message || 'Sorry, I encountered an error. Please try again.',
        timestamp: new Date(),
        isError: true,
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSuggestionClick = (suggestion: string) => {
    setInputValue(suggestion);
  };

  return (
    <Card
      variant="outline"
      borderRadius="xl"
      boxShadow="sm"
      h={{ base: 'calc(100vh - 300px)', lg: 'calc(100vh - 400px)' }}
      minH="400px"
      maxH={{ base: 'calc(100vh - 200px)', lg: 'calc(100vh - 300px)' }}
      display="flex"
      flexDirection="column"
      overflow="hidden"
    >
      <CardHeader pb={3}>
        <Heading size="md" fontWeight="600">AI Assistant</Heading>
      </CardHeader>

      <CardBody display="flex" flexDirection="column" flex={1} pt={0} overflow="hidden">
        <VStack align="stretch" spacing={4} flex={1} overflow="hidden">
          {/* Suggestion Chips */}
          {messages.length === 0 && (
            <Box>
              <Text fontSize="sm" fontWeight="500" color="gray.600" mb={3}>
                Try asking:
              </Text>
              <VStack align="stretch" spacing={2}>
                {SUGGESTION_PROMPTS.map((prompt, index) => (
                  <Button
                    key={index}
                    variant="outline"
                    borderColor="#750926"
                    color="#750926"
                    size="sm"
                    justifyContent="flex-start"
                    textAlign="left"
                    whiteSpace="normal"
                    h="auto"
                    py={2}
                    px={4}
                    borderRadius="full"
                    fontWeight="400"
                    onClick={() => handleSuggestionClick(prompt)}
                    _hover={{
                      bg: '#FFF0F3',
                      borderColor: '#5a0619',
                    }}
                  >
                    {prompt}
                  </Button>
                ))}
              </VStack>
            </Box>
          )}

          {/* AI Response Output Area */}
          <Box
            flex={1}
            bg="gray.50"
            borderRadius="lg"
            p={{ base: 3, md: 4 }}
            overflowY="auto"
            minH="0"
          >
            {messages.length === 0 ? (
              <Flex justify="center" align="center" h="full">
                <Text color="gray.400" fontSize="sm">
                  {proposal.textContent
                    ? 'Ask a question or click a suggestion above'
                    : 'Upload a proposal to start chatting'}
                </Text>
              </Flex>
            ) : (
              <VStack align="stretch" spacing={4}>
                {messages.map(message => (
                  <Box
                    key={message.id}
                    alignSelf={message.role === 'user' ? 'flex-end' : 'flex-start'}
                    maxW="85%"
                  >
                    <Box
                      bg={message.role === 'user' ? '#750926' : 'white'}
                      color={message.role === 'user' ? 'white' : 'gray.800'}
                      px={4}
                      py={3}
                      borderRadius="lg"
                      boxShadow="sm"
                      border={message.role === 'assistant' ? '1px solid' : 'none'}
                      borderColor="gray.200"
                    >
                      <Text fontSize="sm" whiteSpace="pre-wrap">
                        {message.content}
                      </Text>
                      <Text
                        fontSize="xs"
                        mt={1}
                        opacity={0.7}
                      >
                        {message.timestamp.toLocaleTimeString([], {
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </Text>
                    </Box>
                  </Box>
                ))}

                {/* Typing Indicator */}
                {isLoading && (
                  <Box alignSelf="flex-start">
                    <Box bg="white" px={4} py={3} borderRadius="lg" border="1px solid" borderColor="gray.200">
                      <Spinner size="sm" color="#750926" />
                    </Box>
                  </Box>
                )}

                <div ref={messagesEndRef} />
              </VStack>
            )}
          </Box>

          {/* Bottom Chat Input Bar */}
          <HStack spacing={2}>
            <Input
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyPress={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  handleSendMessage();
                }
              }}
              placeholder={
                proposal.textContent
                  ? 'Ask about the proposal or reque…'
                  : 'Upload a proposal to start…'
              }
              disabled={isLoading || !proposal.textContent}
              size="md"
              borderRadius="lg"
              flex={1}
              bg="white"
              borderColor="gray.300"
              _hover={{ borderColor: 'gray.400' }}
              _focus={{
                borderColor: '#750926',
                boxShadow: '0 0 0 1px #750926',
              }}
            />
            <IconButton
              aria-label="Send message"
              icon={<FiSend />}
              onClick={handleSendMessage}
              isDisabled={!inputValue.trim() || isLoading || !proposal.textContent}
              bg="#750926"
              color="white"
              size="md"
              borderRadius="lg"
              _hover={{
                bg: '#5a0619',
              }}
              _active={{
                bg: '#0F3E8C',
              }}
            />
          </HStack>
        </VStack>
      </CardBody>
    </Card>
  );
};

export default ChatInterface;
