import React, { useState, useRef, useEffect } from 'react';
import {
  Box,
  Input,
  VStack,
  HStack,
  Text,
  IconButton,
  Button,
  Card,
  CardBody,
  CardHeader,
  Heading,
  Spinner,
  Flex,
} from '@chakra-ui/react';
import { FiSend } from 'react-icons/fi';
import { useHistory } from 'react-router-dom';
import { useAppStore } from '../../store';
import { sendMessageToGemini } from '../../services/geminiService';
import { Message } from '../../types/chat';
import { Quote, QuoteItem } from '../../types/quote';
import { saveChatHistory, loadChatHistory } from '../../utils/localStorage';

const SUGGESTION_PROMPTS = [
  'Generate quote for 100 auto full branding',
  'Create quote for banner printing 10x5 feet, qty 50',
  'Quote for vehicle branding – 20 tempos',
  'Generate quote for shop signage',
  'Create quote for the services in proposal',
];

const ChatInterface: React.FC = () => {
  const history = useHistory();
  const { proposal, setCurrentQuote } = useAppStore();
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [_error, setError] = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Load chat history on mount
  useEffect(() => {
    const history = loadChatHistory();
    if (history && history.length > 0) {
      setMessages(history.map(msg => ({
        ...msg,
        timestamp: new Date(msg.timestamp),
      })));
    }
  }, []);

  // Save chat history when messages change
  useEffect(() => {
    if (messages.length > 0) {
      saveChatHistory(messages);
    }
  }, [messages]);

  // Scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  const handleSendMessage = async () => {
    if (!inputValue.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: inputValue.trim(),
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    setIsLoading(true);
    setError(null);

    try {
      const response = await sendMessageToGemini({
        userMessage: userMessage.content,
        proposalText: proposal.textContent,
        chatHistory: messages,
      });

      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: response.message,
        timestamp: new Date(),
      };

      setMessages(prev => [...prev, assistantMessage]);

      // If complete quote was generated by AI, store it and AUTO-NAVIGATE
      if (response.isQuoteGeneration && response.quoteData) {
        // Flatten lineItems into individual QuoteItems
        // IMPORTANT: Prepend section title to each description for matching with PDF pages
        const quoteItems: QuoteItem[] = response.quoteData.items.flatMap((section: any, sectionIndex: number) => {
          const sectionTitle = section.title || '';
          return section.lineItems.map((item: any, lineIndex: number) => {
            // If description doesn't already contain the section title, prepend it
            let description = item.description;
            if (sectionTitle && !description.toLowerCase().includes(sectionTitle.toLowerCase())) {
              description = `${sectionTitle} - ${description}`;
            }
            
            const duration = item.duration && item.duration > 1 ? item.duration : undefined;
            return {
              id: `${sectionIndex}-${lineIndex}`,
              description: description,
              quantity: item.quantity || 1,
              rate: item.unitPrice || 0,
              duration: duration,
              total: (item.quantity || 1) * (item.unitPrice || 0) * (duration || 1),
              // Only store terms on the first line item of each section to avoid duplicate textareas
              termsAndConditions: lineIndex === 0 ? (section.termsAndConditions || undefined) : undefined
            };
          });
        });

        const subtotal = quoteItems.reduce((sum, item) => sum + item.total, 0);
        const gstPercentage = 18;
        const gstAmount = subtotal * (gstPercentage / 100);
        
        const quote: Quote = {
          id: Date.now().toString(),
          quoteNumber: `QT-${Date.now().toString().slice(-6)}`,
          date: new Date().toISOString(),
          validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
          items: quoteItems,
          subtotal,
          gstEnabled: true,
          gstPercentage,
          gstAmount,
          total: subtotal + gstAmount,
          deliveryTimeline: response.quoteData.deliveryTimeline || '7 working days after payment',
          termsAndConditions: response.quoteData.termsAndConditions || 'Standard terms and conditions apply',
          notes: response.quoteData.notes,
          createdAt: new Date(),
          updatedAt: new Date()
        };
        
        setCurrentQuote(quote);
        
        // Show success message before navigating
        const quoteReadyMessage: Message = {
          id: (Date.now() + 2).toString(),
          role: 'assistant',
          content: '✓ Quote generated successfully! Redirecting to quote preview...',
          timestamp: new Date(),
        };
        setMessages(prev => [...prev, quoteReadyMessage]);
        
        // Auto-navigate to quote page after a brief delay
        setTimeout(() => {
          history.push('/quote');
        }, 1500);
      }
    } catch (err: any) {
      console.error('Chat error:', err);
      setError(err.message || 'Failed to send message');
      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: err.message || 'Sorry, I encountered an error. Please try again.',
        timestamp: new Date(),
        isError: true,
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSuggestionClick = (suggestion: string) => {
    setInputValue(suggestion);
  };

  return (
    <Box
      display="flex"
      flexDirection="column"
      h={{ base: 'auto', lg: 'calc(100vh - 520px)' }}
      minH={{ base: '350px', lg: '400px' }}
      maxH={{ base: 'calc(100vh - 250px)', lg: 'calc(100vh - 300px)' }}
    >
      {/* Header - AI Assistant with Online Status */}
      <HStack
        justify="space-between"
        align="center"
        px={5}
        py={4}
        borderBottom="1px solid"
        borderColor="gray.200"
      >
        <HStack spacing={2}>
          <Box
            bg="purple.500"
            color="white"
            w="32px"
            h="32px"
            borderRadius="full"
            display="flex"
            alignItems="center"
            justifyContent="center"
            fontSize="sm"
            fontWeight="700"
          >
            G
          </Box>
          <Text fontSize="md" fontWeight="600" color="gray.800">
            Gemini Assistant
          </Text>
        </HStack>
        <HStack spacing={1}>
          <Box w="8px" h="8px" borderRadius="full" bg="green.400" />
          <Text fontSize="xs" color="green.500" fontWeight="500">
            Online
          </Text>
        </HStack>
      </HStack>

      {/* Content Area */}
      <VStack align="stretch" spacing={4} flex={1} overflow="hidden" p={4}>
        {/* Suggestion Chips */}
        {messages.length === 0 && (
          <Box>
            <Text fontSize="sm" fontWeight="500" color="gray.600" mb={3}>
              Try asking:
            </Text>
            <VStack align="stretch" spacing={2}>
              {SUGGESTION_PROMPTS.map((prompt, index) => (
                <Button
                  key={index}
                  variant="outline"
                  borderColor="gray.300"
                  color="gray.700"
                  size="sm"
                  justifyContent="flex-start"
                  textAlign="left"
                  whiteSpace="normal"
                  h="auto"
                  py={2}
                  px={4}
                  borderRadius="full"
                  fontWeight="400"
                  onClick={() => handleSuggestionClick(prompt)}
                  _hover={{
                    bg: 'brand.50',
                    borderColor: 'brand.500',
                    color: 'brand.600',
                  }}
                >
                  {prompt}
                </Button>
              ))}
            </VStack>
          </Box>
        )}

        {/* AI Response Output Area */}
        <Box
          flex={1}
          bg="gray.50"
          borderRadius="lg"
          p={{ base: 3, md: 4 }}
          overflowY="auto"
          minH="0"
        >
          {messages.length === 0 ? (
            <Flex justify="center" align="center" h="full">
              <Text color="gray.500" fontSize="sm">
                {proposal.textContent
                  ? 'Ask a question or click a suggestion above'
                  : 'Upload a proposal to start chatting'}
              </Text>
            </Flex>
          ) : (
            <VStack align="stretch" spacing={4}>
              {messages.map(message => {
                // Parse message content for special formatting
                const lines = message.content.split('\n');
                const hasQuoteHeader = lines[0]?.toLowerCase().includes('quote generated');

                // Helper: bold key summary values
                function boldSummary(line: string) {
                  // Bold numbers and key phrases (e.g., 5 Mobile LED Vans, 3 months)
                  return line.replace(/(\d+\s+Mobile LED Vans|\d+\s+months?|\d+\s+LED vans?|\d+\s+vans?)/gi, '<b>$1</b>');
                }

                return (
                  <Box
                    key={message.id}
                    alignSelf={message.role === 'user' ? 'flex-end' : 'flex-start'}
                    maxW={message.role === 'user' ? '85%' : '95%'}
                  >
                    {message.role === 'assistant' && hasQuoteHeader ? (
                      // Special format for quote generation messages
                      <Box>
                        {/* Quote Header with Icon */}
                        <HStack spacing={2} mb={2} align="flex-start">
                          <Box
                            as="span"
                            color="purple.500"
                            fontSize="lg"
                            mt="2px"
                          >
                            ✓
                          </Box>
                          <Text
                            fontSize="sm"
                            fontWeight="600"
                            color="purple.500"
                          >
                            {lines[0]}
                          </Text>
                        </HStack>

                        {/* Rest of the message */}
                        <Box
                          bg="white"
                          px={4}
                          py={3}
                          borderRadius="lg"
                          boxShadow="0 2px 8px rgba(0, 0, 0, 0.08)"
                        >
                          {lines.slice(1).map((line, idx) => {
                            // Check if this is a code block
                            if (line.includes('```json') || line.includes('"quoteGenerated"') || line.includes('"title"') || line.includes('"lineItems"')) {
                              return null; // Will render code block separately
                            }
                            // Bold summary values
                            return (
                              <Text key={idx} fontSize="sm" color="gray.800" mb={idx === 0 ? 2 : 0} dangerouslySetInnerHTML={{ __html: boldSummary(line) }} />
                            );
                          })}

                          {/* Code Block - if message contains JSON */}
                          {message.content.includes('```json') && (
                            <Box
                              bg="#23272F"
                              color="white"
                              p={3}
                              borderRadius="lg"
                              fontSize="xs"
                              fontFamily="monospace"
                              overflowX="auto"
                              mt={3}
                              maxW="340px"
                              minW="220px"
                              mx="auto"
                              boxShadow="0 1px 4px rgba(0,0,0,0.10)"
                            >
                              <Text whiteSpace="pre" fontSize="xs" fontFamily="monospace">
                                {message.content.match(/```json\n([\s\S]*?)```/)?.[1] || ''}
                              </Text>
                            </Box>
                          )}
                        </Box>
                      </Box>
                    ) : (
                      // Regular message format
                      <Box
                        bg={message.role === 'user' ? 'brand.500' : 'white'}
                        color={message.role === 'user' ? 'white' : 'gray.800'}
                        px={4}
                        py={3}
                        borderRadius="lg"
                        boxShadow={message.role === 'user' ? '0 2px 8px rgba(201, 31, 61, 0.3)' : '0 2px 8px rgba(0, 0, 0, 0.08)'}
                      >
                        <Text fontSize="sm" whiteSpace="pre-wrap">
                          {message.content}
                        </Text>
                        <Text
                          fontSize="xs"
                          mt={1}
                          opacity={0.6}
                        >
                          {message.timestamp.toLocaleTimeString([], {
                            hour: '2-digit',
                            minute: '2-digit',
                          })}
                        </Text>
                      </Box>
                    )}
                  </Box>
                );
              })}

              {/* Typing Indicator */}
              {isLoading && (
                <Box alignSelf="flex-start">
                  <Box bg="white" px={4} py={3} borderRadius="lg" boxShadow="0 2px 8px rgba(0, 0, 0, 0.08)">
                    <Spinner size="sm" color="brand.500" />
                  </Box>
                </Box>
              )}

              <div ref={messagesEndRef} />
            </VStack>
          )}
        </Box>

        {/* Bottom Chat Input Bar */}
        <HStack 
          spacing={2} 
          flexShrink={0} 
          p={4}
        >
          <Input
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyPress={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                handleSendMessage();
              }
            }}
            placeholder={
              proposal.textContent
                ? 'Ask about this proposal...'
                : 'Upload a proposal to start...'
            }
            disabled={isLoading || !proposal.textContent}
            size="md"
            borderRadius="lg"
            bg="white"
            borderColor="gray.200"
            color="gray.800"
            fontSize="16px"
            h="44px"
            w="100%"
            _placeholder={{ color: 'gray.500' }}
            _hover={{ borderColor: 'gray.300' }}
            _focus={{
              borderColor: 'brand.500',
              boxShadow: '0 0 0 1px rgba(201, 31, 61, 0.5)',
            }}
          />
          <IconButton
            aria-label="Send message"
            icon={<FiSend />}
            onClick={handleSendMessage}
            isDisabled={!inputValue.trim() || isLoading || !proposal.textContent}
            bg="brand.500"
            color="white"
            size="md"
            h="44px"
            w="44px"
            minW="44px"
            borderRadius="lg"
            flexShrink={0}
            _hover={{
              bg: 'brand.600',
            }}
            _active={{
              transform: 'scale(0.95)',
            }}
          />
        </HStack>
      </VStack>
    </Box>
  );
};

export default ChatInterface;
